---
# Users
ansible_username: ansible
devops_username: devops

# SSH
ssh:
  login_port: 22

monitor_server_dns: monitor.encapsulate.xyz

# swap
swap:
  size_gb: 32
  file_path: /swapfile
  swappiness_value: 10

# MSMTP
mail:
  to: team@encapsulate.xyz
  from: bot@encapsulate.xyz
  smtp_server: smtp.gmail.com
  port: 587

# Node Exporter
node_exporter_user: node_exporter
node_exporter_port: 9100

# Promtail
promtail_user: promtail
promtail_port: 9080

# Process Exporter
process_exporter_user: process-exporter
process_exporter_port: 9256
