---
system_arch: linux-amd64
tmp_dir: /tmp

# Users
login_users:
  ansible: ansible
  devops: devops

# SSH
ssh:
  ports:
    login: 22

monitor_server_dns: monitor.encapsulate.xyz

# swap
swap:
  size_gb: 32
  file_path: /swapfile
  swappiness_value: 10

# MSMTP
mail:
  to: team@encapsulate.xyz
  from: bot@encapsulate.xyz
  smtp_server: smtp.gmail.com
  port: 587

# Promtail
promtail_user: promtail
promtail_port: 9080

# Process Exporter
process_exporter_user: process-exporter
process_exporter_port: 9256

node_exporter:
  service_identifier: node-exporter
  source_url: https://github.com/prometheus/node_exporter/releases/download
  file_extension: tar.gz
  ports:
    web_listen_address: 9100
