---
- name: Include create user task
  ansible.builtin.include_tasks: tasks/create_user.yml
  vars:
    user_name: "{{ service_identifier }}"
    allow_passwordless_sudo: true
    home: "{{ process_exporter_home_dir }}"

- name: Include create directories task
  ansible.builtin.include_tasks: tasks/create_directories.yml
  vars:
    user: "{{ service_identifier }}"
    directories: "{{ process_exporter_directories }}"
    log_file_path: "{{ process_exporter_log_file_path }}"

- name: Include Download, Unarchive and Copy Binary task
  ansible.builtin.include_tasks: tasks/extract_binary.yml
  vars:
    source_url: "{{ process_exporter.source_url }}/v{{ process_exporter.version }}"
    suffix_url: "{{ process_exporter_default_binary_name }}-{{ process_exporter.version }}.{{ system_arch }}.{{ process_exporter.file_extension }}"
    extracted_binary_path: "{{ process_exporter_extracted_binary_dir }}/{{ process_exporter_default_binary_name }}"
    binary_dest_path: "{{ process_exporter_bin_dir }}/{{ service_identifier }}"

- name: Copy process-exporter config
  ansible.builtin.copy:
    src: process-exporter.yml
    dest: "{{ process_exporter_config_file_path }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    mode: "0644"
  notify:
    - Reload service
    - Restart service

- name: Create process-exporter systemd unit
  ansible.builtin.template:
    src: process-exporter.service.j2
    dest: /etc/systemd/system/{{ service_identifier }}.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload service
    - Restart service
