---
- name: Import setup_server playbook
  ansible.builtin.import_playbook: setup_server.yml

- name: Import setup_security playbook
  ansible.builtin.import_playbook: setup_security.yml

- name: Import promtail playbook
  ansible.builtin.import_playbook: promtail.yml

- name: Import node_exporter playbook
  ansible.builtin.import_playbook: node_exporter.yml

- name: Import process_exporter playbook
  ansible.builtin.import_playbook: process_exporter.yml

- name: Import setup_swap playbook
  ansible.builtin.import_playbook: setup_swap.yml
