---
- name: Install Process Exporter
  hosts: all
  become: true
  gather_facts: false
  vars:
    service_identifier: "{{ process_exporter_user }}"
  vars_files:
    - group_vars/all.yml
    - group_vars/default.yml
  roles:
    - common
    - process_exporter
