---
- name: Setup Security
  hosts: all
  become: true
  gather_facts: true
  vars_files:
    - group_vars/all.yml
    - group_vars/vault.yml
  pre_tasks:
    - name: Resolve IP address from DNS using getent
      ansible.builtin.command: getent ahosts {{ monitor_server_dns }}
      register: dns_result
      changed_when: false

    - name: Extract IP address
      ansible.builtin.set_fact:
        monitor_server_ip: "{{ dns_result.stdout.split()[0] }}"
      changed_when: false
  roles:
    - common
    - security
