---
- name: Setup Swap
  hosts: all
  become: true
  gather_facts: true
  vars_files:
    - group_vars/all.yml

  tasks:
    - name: Setup environment and run nginx role
      when: setup_swap | default(false) | bool
      block:
        - name: Include setup swap role
          ansible.builtin.include_role:
            name: swap
