---
- name: Setup Security
  hosts: all
  become: true
  gather_facts: true
  vars_files:
    - group_vars/all.yml
    - group_vars/vault.yml
  pre_tasks:
    - name: Resolve monitor server domain name to IP
      ansible.builtin.getent:
        database: hosts
        key: "{{ monitor_server_dns }}"
      register: resolved_ip

    - name: Extract IP from getent output
      ansible.builtin.set_fact:
        monitor_server_ip: "{{ resolved_ip.ansible_facts.getent_hosts.keys() | first }}"
  roles:
    - common
    - security
