---
all:
  hosts:
    # Testnet Hub
    176.9.8.81:
      server_name: h1-germany-hub-testnet
      setup_swap: false
      env: testnet
    64.20.36.102:
      server_name: h2-usa-hub-testnet
      setup_swap: false
      env: testnet
    148.113.49.86:
      server_name: h3-india-hub-testnet
      setup_swap: false
      env: testnet
    134.119.182.147:
      server_name: h4-france-hub-testnet
      setup_swap: false
      env: testnet

    # Mainnet Hub
    95.217.50.210:
      server_name: h1-finland-hub-mainnet
      setup_swap: false
      env: mainnet
    135.181.76.221:
      server_name: h2-finland-hub-mainnet
      setup_swap: false
      env: mainnet
    65.109.52.20:
      server_name: h3-finland-hub-mainnet
      setup_swap: false
      env: mainnet
    205.209.104.6:
      server_name: h4-usa-hub-mainnet
      setup_swap: false
      env: mainnet
    139.84.143.106:
      server_name: h5-india-hub-mainnet
      setup_swap: false
      env: mainnet

    # GPU Hub
    204.12.246.220:
      server_name: h1-usa-hub-gpu
      setup_swap: false
      env: mainnet

    # Infra Hub
    65.109.158.204:
      server_name: h1-finland-hub-infra
      setup_swap: false
      env: default

    # Monitor Hub
    65.108.239.113:
      server_name: h1-finland-hub-monitor
      setup_swap: false
      env: default
