---
- name: Download and unarchive the binary
  ansible.builtin.unarchive:
    src: "{{ source_url }}/{{ archive_name }}.{{ file_extension }}"
    dest: "{{ tmp_dir }}"
    remote_src: true
    owner: root
    group: root
    mode: "0755"

- name: Copy the binary file
  ansible.builtin.copy:
    src: "{{ tmp_dir }}/{{ binary_src_path }}"
    dest: "{{ binary_dest_path }}"
    remote_src: true
    owner: root
    group: root
    force: true
    mode: "0755"

- name: Clean up the temporary files in /tmp
  ansible.builtin.file:
    path: "{{ tmp_dir }}/{{ binary_src_path }}"
    state: absent
