---
- name: Add email notification settings to sudoers
  lineinfile:
    path: /etc/sudoers
    state: present
    line: "{{ item }}"
    validate: '/usr/sbin/visudo -cf %s'
  loop:
    - 'Defaults mail_always'
    - 'Defaults mailto="{{ mail_to }}"'
    - 'Defaults mailerpath=/usr/sbin/sendmail'
    - 'Defaults:ansible !mail_always'