---
- name: Add email notification settings to sudoers
  ansible.builtin.lineinfile:
    path: "{{ security_sudoers.config_file }}"
    state: present
    line: "{{ item }}"
    validate: /usr/sbin/visudo -cf %s
  loop:
    - Defaults mail_always
    - Defaults mailto="{{ mail.to }}"
    - Defaults mailerpath=/usr/sbin/sendmail
    - Defaults:ansible !mail_always

- name: Copy sudoers file for devops
  ansible.builtin.copy:
    src: sudoers_devops
    dest: "{{ security_sudoers.devops_file }}"
    owner: root
    group: root
    mode: '0440'
