- name: Install auditd
  apt:
    name:
      - auditd
      - audispd-plugins
      - logrotate
    state: present

- name: Remove default auditd rules
  file:
    path: /etc/audit/rules.d/audit.rules
    state: absent

- name: Copy audit.rules service file
  copy:
    src: 'audit.rules'
    dest: '/etc/audit/rules.d/audit.rules'
    owner: root
    group: root
    mode: '0640'

- name: Ensure auditd service is enabled and started
  systemd:
    name: auditd
    state: restarted
    enabled: yes
  changed_when: false
