---
- name: Set service identifier
  ansible.builtin.set_fact:
    service_identifier: "{{ ssh.service_identifier }}"

- name: Install ufw
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: true

- name: Enable firewall
  community.general.ufw:
    state: enabled
    logging: medium

- name: Open ssh port
  community.general.ufw:
    rule: limit
    port: "{{ ssh.ports.login }}"
    proto: tcp
    comment: Allow SSH

- name: Allow traffic from Monitor Server to Node Exporter
  community.general.ufw:
    rule: allow
    from_ip: "{{ monitor_server_ip }}"
    to_port: "{{ node_exporter.ports.web_listen_address }}"
    proto: tcp
    comment: Allow traffic from Monitor Server to Node Exporter

- name: Allow traffic from Monitor Server to Process Exporter
  community.general.ufw:
    rule: allow
    from_ip: "{{ monitor_server_ip }}"
    to_port: "{{ process_exporter.ports.web_listen_address }}"
    proto: tcp
    comment: Allow traffic from Monitor Server to Process Exporter

- name: Disable root login over SSH
  ansible.builtin.lineinfile:
    dest: "{{ security_ssh.sshd_config_file_path }}"
    regexp: ^PermitRootLogin
    line: PermitRootLogin no
    state: present
  notify:
    - Restart service

- name: Disable password login
  ansible.builtin.lineinfile:
    dest: "{{ security_ssh.sshd_config_file_path }}"
    regexp: ^PasswordAuthentication
    line: PasswordAuthentication no
    state: present
  notify:
    - Restart service

- name: Copy vault.pub to trusted CA path
  ansible.builtin.copy:
    src: vault.pub
    dest: "{{ security_ssh.trusted_ca_file_path }}"
    owner: root
    group: root
    mode: "0644"

# Configure SSH to use vault.pub as the Trusted User CA key
- name: Configure SSH for Trusted User CA
  ansible.builtin.lineinfile:
    path: "{{ security_ssh.sshd_config_file_path }}"
    regexp: ^TrustedUserCAKeys
    line: TrustedUserCAKeys {{ security_ssh.trusted_ca_file_path }}
    state: present
  notify:
    - Restart service
