---
- name: Install packages
  apt:
    name: 
      - msmtp
      - msmtp-mta
      - mailutils
      - postfix
    state: present

- name: Configure msmtp mail settings
  blockinfile:
    path: /etc/msmtprc
    block: |
      defaults
      port {{ mail_port }}
      tls on
      tls_trust_file /etc/ssl/certs/ca-certificates.crt
      account {{ mail_from }}
      host {{ mail_smtp_server }}
      set_from_header on
      from {{ mail_from }}
      auth on
      user {{ mail_from }}
      password {{ mail_pw }}
      account default: {{ mail_from }}
      aliases /etc/aliases
      logfile /var/log/msmtp
    create: true

- name: Set chmod for mail config file
  file:
    path: /etc/msmtprc
    group: msmtp
    mode: '640'

- name: Configure email alias forwarding
  lineinfile:
    dest: /etc/aliases
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    create: true
  loop:
    - { regexp: '^root:', line: 'root: {{ mail_to }}' }
    - { regexp: '^default:', line: 'default: {{ mail_to }}' }

- name: set msmtp as default mail handler
  lineinfile:
    path: /etc/mail.rc
    regexp: '^set sendmail'
    line: 'set sendmail="/usr/bin/msmtp -t"'
    create: yes

- name: send a testmail
  shell: echo "Testmail content" | mail -s "Testmail subject" {{ mail_to }}

- name: Create logrotate configuration for /var/spool/mail/root and /var/mail/root
  copy:
    dest: /etc/logrotate.d/mailroot
    content: |
      /var/spool/mail/root /var/mail/root {
          weekly
          rotate 4
          compress
          delaycompress
          missingok
          notifempty
          create 0600 root root
          su root root
      }

- name: Create logrotate configuration for msmtp
  copy:
    dest: /etc/logrotate.d/msmtp
    content: |
      /var/log/msmtp {
          weekly
          rotate 4
          missingok          
          compress
          delaycompress
          notifempty
          create 0640 root root
          su root root
      }