---
- name: Install ufw
  apt:
    name: ufw
    state: present
    update_cache: yes

- name: Enable firewall
  ufw:
    state: enabled
    logging: on

- name: Open ssh port
  ufw:
    rule: limit
    port: '{{ ssh_port }}'
    proto: tcp
    comment: 'Allow SSH'

- name: Allow traffic from Monitor Server to Node Exporter 
  ufw:
    rule: allow
    from_ip: "{{ monitor_server_ip }}"
    to_port: 9100
    proto: tcp
    comment: 'Allow traffic from Monitor Server to Node Exporter'

- name: Allow traffic from Monitor Server to Process Exporter
  ufw:
    rule: allow
    from_ip: "{{ monitor_server_ip }}"
    to_port: 9256
    proto: tcp
    comment: 'Allow traffic from Monitor Server to Process Exporter'

- name: Disable root login over SSH
  lineinfile:
    dest: '/etc/ssh/sshd_config'
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present
  when: disable_root|default(true)|bool == true

- name: Disable password login
  lineinfile:
    dest: '/etc/ssh/sshd_config'
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present

- name: Restart SSH
  service:
    name: ssh
    state: restarted
  changed_when: false
