---
- name: Create logrotate configuration for audit logs
  ansible.builtin.template:
    src: logrotate.j2
    dest: "{{ security_logrotate.auditd_config_file }}"
    mode: "0644"
  vars:
    log_path: "{{ security_logrotate.auditd_logs_path }}"

- name: Create logrotate configuration for /var/spool/mail/root and /var/mail/root
  ansible.builtin.template:
    src: logrotate.j2
    dest: "{{ security_logrotate.mailroot_config_file }}"
    mode: "0644"
  vars:
    log_path: "{{ security_logrotate.mailroot_logs_path }}"

- name: Create logrotate configuration for msmtp
  ansible.builtin.template:
    src: logrotate.j2
    dest: "{{ security_logrotate.msmtp_config_file }}"
    mode: "0644"
  vars:
    log_path: "{{ security_logrotate.msmtp_logs_path }}"

- name: Create logrotate configuration for rkhunter
  ansible.builtin.template:
    src: logrotate.j2
    dest: "{{ security_logrotate.rkhunter_config_file }}"
    mode: "0644"
  vars:
    log_path: "{{ security_logrotate.rkhunter_logs_path }}"
