---
- name: Set service identifier
  ansible.builtin.set_fact:
    service_identifier: fail2ban

- name: Include install packages task
  ansible.builtin.include_tasks: tasks/install_packages.yml
  vars:
    packages:
      - fail2ban

- name: Configure ssh jail
  ansible.builtin.blockinfile:
    path: "{{ security_fail2ban.config_file }}"
    block: |
      [sshd]
      enabled = true
      banaction = ufw
      port = {{ ssh.ports.login | default('ssh') }}
      filter = sshd
      logpath = {{ security_fail2ban.log_file }}
      maxretry = 5
      findtime = 86400
      bantime  = -1
    create: true
    mode: "0644"
  notify:
    - Reload service
    - Restart service
