---
- name: Configure SSH
  ansible.builtin.import_tasks: configure_ssh.yml

- name: Configure fail2ban
  ansible.builtin.import_tasks: configure_fail2ban.yml

- name: Configure auditd
  ansible.builtin.import_tasks: configure_auditd.yml

- name: Configure msmtp
  ansible.builtin.import_tasks: configure_msmtp.yml

- name: Configure rkhunter
  ansible.builtin.import_tasks: configure_rkhunter.yml

- name: Configure logrotate
  ansible.builtin.import_tasks: configure_logrotate.yml

- name: Configure sudoers file
  ansible.builtin.import_tasks: configure_sudoers.yml
