---
- name: Configure SSH
  import_tasks: configure_ssh.yml
  when: ssh|default(true)|bool == true

- name: Configure fail2ban
  import_tasks: configure_fail2ban.yml
  when: fail2ban|default(true)|bool == true

- name: Configure auditd
  import_tasks: configure_auditd.yml
  when: auditd|default(true)|bool == true

- name: Configure msmtp
  import_tasks: configure_msmtp.yml
  when: msmtp|default(true)|bool == true

- name: Configure rkhunter
  import_tasks: configure_rkhunter.yml
  when: rkhunter|default(true)|bool == true

- name: Configure psad
  import_tasks: configure_psad.yml
  when: psad|default(true)|bool == true

- name: Configure logwatch
  import_tasks: configure_logwatch.yml
  when: logwatch|default(false)|bool == true

- name: Configure lynis
  import_tasks: configure_lynis.yml
  when: lynis|default(false)|bool == true

- name: Configure clamav
  import_tasks: configure_clamav.yml
  when: clamav|default(false)|bool == true

- name: Configure aide
  import_tasks: configure_aide.yml
  when: aide|default(true)|bool == true
