---
- name: Configure SSH
  import_tasks: configure_ssh.yml

- name: Configure fail2ban
  import_tasks: configure_fail2ban.yml

- name: Configure auditd
  import_tasks: configure_auditd.yml

- name: Configure msmtp
  import_tasks: configure_msmtp.yml

- name: Configure rkhunter
  import_tasks: configure_rkhunter.yml

- name: Configure psad
  import_tasks: configure_psad.yml

- name: Configure logwatch
  import_tasks: configure_logwatch.yml

- name: Configure lynis
  import_tasks: configure_lynis.yml
  