---
- name: Include create user task
  ansible.builtin.include_tasks: tasks/create_user.yml
  vars:
    user_name: "{{ service_identifier }}"
    allow_passwordless_sudo: true
    home: "{{ node_exporter_home_dir }}"

- name: Include create directories task
  ansible.builtin.include_tasks: tasks/create_directories.yml
  vars:
    user: "{{ service_identifier }}"
    directories: "{{ node_exporter_directories }}"
    log_file_path: "{{ node_exporter_log_file_path }}"

- name: Include Download, Unarchive and Copy Binary task
  ansible.builtin.include_tasks: tasks/download_unarchive_and_copy_binary.yml
  vars:
    download_url: "{{ node_exporter_url }}"
    download_dest: "{{ node_exporter_binary_archive_file_name }}"
    archive_src: "{{ node_exporter_binary_archive_file_name }}"
    unarchive_dest: "{{ node_exporter_binary_unarchive_dir }}"
    binary_src: "{{ node_exporter_binary_file }}"
    binary_dest: "{{ node_exporter_bin_dir }}"
    user: "{{ service_identifier }}"

- name: Create systemd unit file for node exporter
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/{{ service_identifier }}.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload service
    - Restart service
