---
- name: Reload service
  ansible.builtin.systemd:
    name: "{{ service_name }}"
    state: reloaded

- name: Start service
  ansible.builtin.systemd:
    name: "{{ service_name }}"
    state: started
    enabled: true

- name: Restart service
  ansible.builtin.systemd:
    name: "{{ service_name }}"
    state: restarted

- name: Stop service
  ansible.builtin.systemd:
    name: "{{ service_name }}"
    state: stopped
