---
- name: Include create user task for ansible user
  ansible.builtin.include_tasks: tasks/create_user.yml
  vars:
    shell: /bin/bash
    is_system_user: false
    user_name: "{{ setup.login_users.ansible }}"
    allow_passwordless_sudo: true

- name: Include create user task for devops user
  ansible.builtin.include_tasks: tasks/create_user.yml
  vars:
    shell: /bin/bash
    is_system_user: false
    user_name: "{{ setup.login_users.devops }}"
    user_groups: [adm, systemd-journal]
    user_password: "{{ vault.users.devops.password }}"

- name: Add authorized key for ansible user
  ansible.posix.authorized_key:
    user: "{{ setup.login_users.ansible }}"
    key: "{{ lookup('file', 'ansible.pub') }}"
    exclusive: true
