---
- name: Get swap file path from /etc/fstab
  shell: grep swap /etc/fstab | awk '{print $1}'
  register: current_swap_file_path_result
  changed_when: false

- name: Set the current swap file path variable
  set_fact:
    current_swap_file_path: "{{ current_swap_file_path_result.stdout.strip() }}"
  when: current_swap_file_path_result.stdout.strip() != ''

- name: Disable swap if it exists
  command: swapoff -a
  when: current_swap_file_path is defined
  ignore_errors: true

- name: Remove existing swap file
  file:
    path: "{{ current_swap_file_path }}"
    state: absent
  when: current_swap_file_path is defined

- name: Create swap file 
  command: fallocate -l {{ swap_size_gb }}G {{ swap_file_path }}

- name: Set swap file permissions
  file:
    path: "{{ swap_file_path }}"
    owner: root
    group: root
    mode: '0600'

- name: Make swap
  command: mkswap {{ swap_file_path }}

- name: Enable swap
  command: swapon {{ swap_file_path }}

- name: Add swap to fstab
  lineinfile:
    path: /etc/fstab
    line: "{{ swap_file_path }} none swap sw 0 0"
    state: present

- name: Get current swappiness value
  command: cat /proc/sys/vm/swappiness
  register: current_swappiness
  changed_when: false

- name: Set swappiness
  sysctl:
    name: vm.swappiness
    value: "{{ swappiness_value }}"
    state: present
  when: current_swappiness.stdout | int != swappiness_value

- name: Ensure swappiness in sysctl.conf
  lineinfile:
    path: /etc/sysctl.conf
    line: "vm.swappiness={{ swappiness_value }}"
    state: present
