---
- name: Check if swap file exists
  stat:
    path: "{{ swap_file_path }}"
  register: swap_file

- name: Check current swap size
  shell: free -g | awk '/^Swap:/ {print $2}'
  register: current_swap_size
  changed_when: false

- name: Disable swap if it exists
  command: swapoff -a
  when: swap_file.stat.exists
  ignore_errors: true

- name: Remove existing swap file
  file:
    path: "{{ swap_file_path }}"
    state: absent
  when: swap_file.stat.exists and current_swap_size.stdout | int != swap_size_gb

- name: Create swap file 
  command: fallocate -l {{ swap_size_gb }}G /swapfile
  when: not swap_file.stat.exists or current_swap_size.stdout | int != swap_size_gb

- name: Set swap file permissions
  file:
    path: "{{ swap_file_path }}"
    owner: root
    group: root
    mode: '0600'

- name: Make swap
  command: mkswap {{ swap_file_path }}
  when: not swap_file.stat.exists or current_swap_size.stdout | int != swap_size_gb

- name: Enable swap
  command: swapon {{ swap_file_path }}
  when: not swap_file.stat.exists or current_swap_size.stdout | int != swap_size_gb

- name: Add swap to fstab
  lineinfile:
    path: /etc/fstab
    line: "{{ swap_file_path }} none swap sw 0 0"
    state: present

- name: Get current swappiness value
  command: cat /proc/sys/vm/swappiness
  register: current_swappiness
  changed_when: false

- name: Set swappiness
  sysctl:
    name: vm.swappiness
    value: "{{ swappiness_value }}"
    state: present
  when: current_swappiness.stdout | int != swappiness_value

- name: Ensure swappiness in sysctl.conf
  lineinfile:
    path: /etc/sysctl.conf
    line: "vm.swappiness={{ swappiness_value }}"
    state: present
