---
- name: Create Ansible user
  user:
    name: "{{ item }}"
    shell: /bin/bash
  loop: 
    - 'ansible'
    - 'devops'

- name: Add ansible authorized key
  authorized_key:
    user: ansible
    key: "{{ lookup('file', playbook_dir + '/keys/ansible.pub') }}"
    exclusive: yes

- name: Add devops authorized key
  authorized_key:
    user: devops
    key: "{{ lookup('file', playbook_dir + '/keys/devops.pub') }}"
    exclusive: yes

- name: Allow sudo for ansible
  copy:
    content: 'ansible ALL=(ALL) NOPASSWD: ALL'
    dest: /etc/sudoers.d/ansible
    mode: '0600'
