---
- name: Include create user task
  ansible.builtin.include_tasks: tasks/create_user.yml
  vars:
    shell: /bin/bash
    user:
      - { name: "{{ ansible_username }}", nopasswd: true }
      - { name: "{{ devops_username }}", nopasswd: false, groups: [adm, systemd-journal] }

- name: Add authorized keys for ansible and devops
  ansible.posix.authorized_key:
    user: "{{ item.user }}"
    key: "{{ lookup('file', playbook_dir + '/keys/' + item.key) }}"
    exclusive: true
  loop:
    - { user: "{{ ansible_username }}", key: "{{ ansible_username }}.pub" }
    - { user: "{{ devops_username }}", key: "{{ devops_username }}.pub" }
