---
- name: Create Ansible user
  user:
    name: "{{ item }}"
    shell: /bin/bash
  loop:
    - 'ansible'
    - 'devops'

- name: Add authorized keys for ansible and devops
  authorized_key:
    user: "{{ item.user }}"
    key: "{{ lookup('file', playbook_dir + '/keys/' + item.key) }}"
    exclusive: yes
  loop:
    - { user: 'ansible', key: 'ansible.pub' }
    - { user: 'devops', key: 'devops.pub' }

- name: Configure permissions for ansible and devops users
  block:
    - name: Allow sudo for ansible
      copy:
        content: 'ansible ALL=(ALL) NOPASSWD: ALL'
        dest: /etc/sudoers.d/ansible
        mode: '0600'

    - name: Add devops user to adm and systemd-journal groups
      user:
        name: devops
        groups: [ 'adm', 'systemd-journal' ]
        append: yes
