---
- name: Create Ansible user
  user:
    name: ansible
    shell: /bin/bash

- name: Add ansible authorized key
  authorized_key:
    user: ansible
    key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
    exclusive: yes

- name: Allow sudo for ansible
  copy:
    content: 'ansible ALL=(ALL) NOPASSWD: ALL'
    dest: /etc/sudoers.d/ansible
    mode: '0600'