---
- name: Download node_exporter
  get_url:
    url: 'https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz'
    dest: '/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz'
    mode: '0700'

- name: Unarchive node_exporter
  unarchive:
    src: '/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz'
    remote_src: true
    dest: '/tmp'

- name: Copy node_exporter binary
  copy:
    src: '/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter'
    dest: '/usr/local/bin/'
    remote_src: true
    owner: root
    group: root
    mode: '0755'

- name: Create node_exporter systemd unit
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: '0600'

- name: Start node_exporter service
  systemd:
    name: node_exporter
    state: restarted
    daemon_reload: yes
    enabled: yes
  changed_when: false