---
- name: Install node exporter
  import_tasks: install_node_exporter.yml

- name: Install promtail
  import_tasks: install_promtail.yml
  
- name: Install process exporter
  import_tasks: install_process_exporter.yml