---
- name: Install basic packages
  ansible.builtin.include_tasks: tasks/install_packages.yml
  vars:
    packages:
      - build-essential
      - cargo

- name: Create Users
  ansible.builtin.include_tasks: create_users.yml

- name: Install Node Exporter
  ansible.builtin.include_tasks: install_node_exporter.yml

- name: Install Promtail
  ansible.builtin.include_tasks: install_promtail.yml

- name: Install Process Exporter
  ansible.builtin.include_tasks: install_process_exporter.yml

- name: Configure SWAP
  ansible.builtin.include_tasks: configure_swap.yml

- name: Setup tailf
  ansible.builtin.include_tasks: create_tailf.yml
