---
- name: Install basic packages
  ansible.builtin.include_tasks: tasks/install_packages.yml
  vars:
    packages:
      - build-essential
      - cargo

- name: Create Users
  ansible.builtin.include_tasks: create_users.yml

- name: Configure SWAP
  ansible.builtin.include_tasks: configure_swap.yml

- name: Setup tailf
  ansible.builtin.include_tasks: create_tailf.yml
