---
- name: Install essential packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - build-essential
    - cargo
    - unzip

- name: Create Users
  ansible.builtin.include_tasks: create_users.yml

- name: Configure SWAP
  ansible.builtin.include_tasks: configure_swap.yml

- name: Setup tailf
  ansible.builtin.include_tasks: create_tailf.yml
